#!/usr/bin/env python3
"""
Unified paper figure pipeline — generates Figs 3–10 from FLOODABM outputs.

Usage:
    python generate_paper_figures.py                        # all figures, default root
    python generate_paper_figures.py --root outputs/thr050  # different output root
    python generate_paper_figures.py --figs 4 5 6 7         # specific figures only
    python generate_paper_figures.py --list                 # show figure registry

Each figure delegates to its source script. When --root is given, the
FLOODABM_OUTPUT_ROOT environment variable is set so scripts can optionally
read it instead of their hardcoded paths.

Figure registry (updated 2026-03-07):
    Fig 3  — NFIP z-score validation
    Fig 4  — RQ1 damage & loss ratio by tenure
    Fig 5  — RQ1 finance panels (same script as Fig 4)
    Fig 6  — Cumulative adaptive behavior composition
    Fig 7  — Annual adoption rate divergence (2-panel)
    Fig 9  — SA ratio-threshold delta grid (2×2)
    Fig 10 — TP boxplot by year

    Fig 1 (study area), Fig 2 (flowchart), Fig 8 (spatial map) are static assets.
"""
import argparse
import os
import subprocess
import sys
from pathlib import Path

# ── Figure registry ──────────────────────────────────────────────────────────
# Maps figure number → (script_path, description, extra_args)
FIGURES = {
    3: ("scripts/paper_figures/plot_nfip_validation_paper.py",
        "NFIP z-score validation (county-level)", []),
    4: ("scripts/paper_figures/plot_fig_rq1_combined.py",
        "RQ1 — damage & loss ratio by tenure (Fig 4 + Fig 5)", []),
    5: ("scripts/paper_figures/plot_fig_rq1_combined.py",
        "RQ1 — finance panels (generated together with Fig 4)", []),
    6: ("scripts/paper_figures/plot_fig_cumulative_behavior.py",
        "Cumulative adaptive behavior composition", []),
    7: ("scripts/paper_figures/plot_fig7_v2_2panel.py",
        "Annual adoption rate divergence (2-panel)", []),
    9: ("scripts/paper_figures/plot_sa_rt_delta.py",
        "SA ratio-threshold delta grid (2x2)", []),
    10: ("scripts/paper_figures/plot_fig10_tp_boxplot.py",
        "TP boxplot by year (homeowner vs renter)", []),
}

# Figs 4 & 5 come from the same script — deduplicate
_ALREADY_RAN = set()


def run_figure(fig_num: int, root: str | None, dry_run: bool = False) -> bool:
    """Run the script for a single figure. Returns True on success."""
    script, desc, extra = FIGURES[fig_num]

    # Deduplicate (Figs 4 & 5 share a script)
    key = script
    if key in _ALREADY_RAN:
        print(f"  [skip] Fig {fig_num}: already generated by {script}")
        return True
    _ALREADY_RAN.add(key)

    print(f"  [Fig {fig_num}] {desc}")
    print(f"          → {script}")

    if dry_run:
        return True

    env = os.environ.copy()
    # Ensure scripts can import from project root (utils/, core/, modules/)
    project_root = str(Path(__file__).resolve().parent)
    env["PYTHONPATH"] = project_root + os.pathsep + env.get("PYTHONPATH", "")
    if root:
        env["FLOODABM_OUTPUT_ROOT"] = root

    cmd = [sys.executable, script] + extra
    try:
        result = subprocess.run(
            cmd, env=env, cwd=project_root,
            capture_output=True, text=True, timeout=300,
            encoding="utf-8", errors="replace",
        )
        if result.returncode != 0:
            print(f"  [FAIL] exit code {result.returncode}")
            if result.stderr:
                for line in result.stderr.strip().splitlines()[-5:]:
                    print(f"         {line}")
            return False
        print(f"  [OK]")
        return True
    except subprocess.TimeoutExpired:
        print(f"  [TIMEOUT] after 300s")
        return False
    except Exception as e:
        print(f"  [ERROR] {e}")
        return False


def main():
    parser = argparse.ArgumentParser(
        description="Generate paper figures 3–10 from FLOODABM outputs."
    )
    parser.add_argument(
        "--root", type=str, default=None,
        help="Output root directory (default: outputs/baseline/baseline)"
    )
    parser.add_argument(
        "--figs", type=int, nargs="+", default=None,
        help="Figure numbers to generate (default: all 3–9)"
    )
    parser.add_argument(
        "--list", action="store_true",
        help="List available figures and exit"
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Show what would be run without executing"
    )
    args = parser.parse_args()

    if args.list:
        print("Available figures:")
        for num, (script, desc, _) in sorted(FIGURES.items()):
            print(f"  Fig {num}: {desc}  [{script}]")
        return

    figs = args.figs or sorted(FIGURES.keys())
    invalid = [f for f in figs if f not in FIGURES]
    if invalid:
        print(f"Unknown figure(s): {invalid}. Valid: {sorted(FIGURES.keys())}")
        sys.exit(1)

    print(f"{'=' * 60}")
    print(f"FLOODABM Paper Figure Pipeline")
    print(f"Root: {args.root or 'outputs/baseline/baseline (default)'}")
    print(f"Figures: {figs}")
    print(f"{'=' * 60}")

    ok, fail = 0, 0
    for fig_num in figs:
        success = run_figure(fig_num, args.root, args.dry_run)
        if success:
            ok += 1
        else:
            fail += 1

    print(f"\n{'=' * 60}")
    print(f"Done: {ok} succeeded, {fail} failed")
    if fail:
        sys.exit(1)


if __name__ == "__main__":
    main()
