#!/usr/bin/env python3
"""
Unified paper figure pipeline for FLOODABM (Water Resources Research).

Usage:
    python generate_paper_figures.py                  # all registered figure scripts
    python generate_paper_figures.py --root <dir>     # different output root
    python generate_paper_figures.py --figs 6 7       # specific figures only
    python generate_paper_figures.py --list           # show the figure registry

Each entry delegates to its source script. When --root is given, the
FLOODABM_OUTPUT_ROOT environment variable is set so scripts can optionally
read it instead of their default paths. The figure scripts read from a Monte
Carlo output tree (50 stochastic runs); see the README for how it is produced.

Registry follows the Water Resources Research manuscript numbering:
    Fig 5  — NFIP avg payout per claim (z-score), 50-run median + IQR
    Fig 6  — cumulative ground-up and actual loss per household
    Fig 7  — financial outcomes and loss AEP curves (same script as Fig 6)
    Fig 9  — tract-level mean threat perception, flood-prone vs non-prone
    Fig 11 — income-normalized AEP (loss as % of tenure median household income)

Prepared outside this pipeline:
    Fig 1 (study area), Fig 2 (Bayesian procedure), Fig 3 (flowchart), and
    Fig 4 (flood-model diagnostics) are static / external assets.
    Fig 8 (adaptation trajectories) is rendered by the adoption scripts in
    scripts/paper_figures/ (plot_fig7_v2_2panel.py, plot_fig_cumulative_behavior.py).
    Fig 10 spatial FI maps and SI Fig S4 population maps are drawn externally
    in ArcGIS from the CSVs written by scripts/utilities/gen_spatial_*_mc50.py.
"""
import argparse
import os
import subprocess
import sys
from pathlib import Path

# ── Figure registry ──────────────────────────────────────────────────────────
# Maps figure number → (script_path, description, extra_args)
FIGURES = {
    5: ("scripts/paper_figures/plot_fig5_nfip_validation.py",
        "NFIP avg payout per claim (z-score), 3 counties on one panel, 50-run median + IQR", []),
    6: ("scripts/paper_figures/plot_fig_rq1_combined.py",
        "cumulative ground-up & actual loss per household (also renders Fig 7)", []),
    7: ("scripts/paper_figures/plot_fig_rq1_combined.py",
        "financial outcomes & loss AEP curves (generated together with Fig 6)", []),
    9: ("scripts/paper_figures/plot_fig8_tp_by_prone.py",
        "tract-level mean threat perception, flood-prone vs non-prone", []),
    11: ("scripts/paper_figures/plot_fig11_income_aep.py",
        "income-normalized AEP of household loss (% of tenure median income)", []),
}

# Figs 6 & 7 come from the same script — deduplicate
_ALREADY_RAN = set()


def run_figure(fig_num: int, root: str | None, dry_run: bool = False) -> bool:
    """Run the script for a single figure. Returns True on success."""
    script, desc, extra = FIGURES[fig_num]

    # Deduplicate (Figs 4 & 5 share a script)
    key = script
    if key in _ALREADY_RAN:
        print(f"  [skip] Fig {fig_num}: already generated by {script}")
        return True
    _ALREADY_RAN.add(key)

    print(f"  [Fig {fig_num}] {desc}")
    print(f"          → {script}")

    if dry_run:
        return True

    env = os.environ.copy()
    # Ensure scripts can import from project root (utils/, core/, modules/)
    project_root = str(Path(__file__).resolve().parent)
    env["PYTHONPATH"] = project_root + os.pathsep + env.get("PYTHONPATH", "")
    if root:
        env["FLOODABM_OUTPUT_ROOT"] = root

    cmd = [sys.executable, script] + extra
    try:
        result = subprocess.run(
            cmd, env=env, cwd=project_root,
            capture_output=True, text=True, timeout=300,
            encoding="utf-8", errors="replace",
        )
        if result.returncode != 0:
            print(f"  [FAIL] exit code {result.returncode}")
            if result.stderr:
                for line in result.stderr.strip().splitlines()[-5:]:
                    print(f"         {line}")
            return False
        print(f"  [OK]")
        return True
    except subprocess.TimeoutExpired:
        print(f"  [TIMEOUT] after 300s")
        return False
    except Exception as e:
        print(f"  [ERROR] {e}")
        return False


def main():
    parser = argparse.ArgumentParser(
        description="Generate Water Resources Research manuscript figures from FLOODABM outputs."
    )
    parser.add_argument(
        "--root", type=str, default=None,
        help="Output root directory (default: outputs/baseline/baseline)"
    )
    parser.add_argument(
        "--figs", type=int, nargs="+", default=None,
        help="Manuscript figure numbers to generate (default: all registered)"
    )
    parser.add_argument(
        "--list", action="store_true",
        help="List available figures and exit"
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Show what would be run without executing"
    )
    args = parser.parse_args()

    if args.list:
        print("Available figures:")
        for num, (script, desc, _) in sorted(FIGURES.items()):
            print(f"  Fig {num}: {desc}  [{script}]")
        return

    figs = args.figs or sorted(FIGURES.keys())
    invalid = [f for f in figs if f not in FIGURES]
    if invalid:
        print(f"Unknown figure(s): {invalid}. Valid: {sorted(FIGURES.keys())}")
        sys.exit(1)

    print(f"{'=' * 60}")
    print(f"FLOODABM Paper Figure Pipeline")
    print(f"Root: {args.root or 'outputs/baseline/baseline (default)'}")
    print(f"Figures: {figs}")
    print(f"{'=' * 60}")

    ok, fail = 0, 0
    for fig_num in figs:
        success = run_figure(fig_num, args.root, args.dry_run)
        if success:
            ok += 1
        else:
            fail += 1

    print(f"\n{'=' * 60}")
    print(f"Done: {ok} succeeded, {fail} failed")
    if fail:
        sys.exit(1)


if __name__ == "__main__":
    main()
