# -*- coding: utf-8 -*-
"""
SA Output Manager — Selective Output Strategy for Sensitivity Analysis
========================================================================

Manages what outputs to save during sensitivity analysis runs to optimize storage.

Modes:
- 'full': Save everything (current behavior) ~250MB per run
- 'summary': Save only aggregated statistics ~10MB per run  
- 'minimal': Save only essential final statistics ~1MB per run

Usage:
    output_mgr = SAOutputManager(mode='summary')
    
    # Check if specific output should be saved
    if output_mgr.should_save('finance_households'):
        df.to_csv(...)
    
    # Save summary statistics instead
    output_mgr.save_summary_statistics(data, output_path)
"""

from __future__ import annotations
from pathlib import Path
from typing import Dict, List, Any, Optional
import pandas as pd
import numpy as np
import json


class SAOutputManager:
    """Manages selective output saving for sensitivity analysis runs."""
    
    # Output types categorized by importance
    # ESSENTIAL_OUTPUTS are always saved in all modes (needed for SA + baseline plots)
    ESSENTIAL_OUTPUTS = {
        # Finance aggregates (for payout, premium, OOP charts)
        'finance_tract_all_years',
        
        # Damage aggregates (for damage charts)
        'flood_damage_tract_ALL_years',
        
        # Decision aggregates - all years file
        'action_share_all_years',
        
        # Decision files - key years only (2011, 2014, 2021, 2023)
        'action_share_2011',
        'action_share_2014',
        'action_share_2021',
        'action_share_2023',
        
        # Summary JSON
        'output_summary_json',
    }
    
    # DETAIL_OUTPUTS are only saved in 'full' mode (large files not needed for plots)
    DETAIL_OUTPUTS = {
        'finance_households',           # Per-household finance (100MB+, not needed)
        'state_csvs',                   # Year-end state files (15MB, not needed)
        'excel',                        # Excel exports (50MB, optional)
        'visualization_png',            # Individual plots (20MB, regenerated by SA)
        
        # Decision files for non-key years (can skip to save space)
        'action_share_2012',
        'action_share_2013',
        'action_share_2015',
        'action_share_2016',
        'action_share_2017',
        'action_share_2018',
        'action_share_2019',
        'action_share_2020',
        'action_share_2022',
    }
    
    INTERMEDIATE_OUTPUTS = {
        'debug_files',                  # Debug/diagnostic files
    }
    
    def __init__(self, mode: str = 'summary', output_dir: Optional[Path] = None):
        """
        Initialize output manager.
        
        Args:
            mode: Output level - 'full', 'summary', or 'minimal'
            output_dir: Base output directory for this run
        """
        if mode not in ['full', 'summary', 'minimal']:
            raise ValueError(f"Invalid mode: {mode}. Must be 'full', 'summary', or 'minimal'")
        
        self.mode = mode
        self.output_dir = Path(output_dir) if output_dir else None
        self.statistics = {}  # Store incremental statistics
        
    def should_save(self, output_type: str) -> bool:
        """
        Determine if output should be saved based on current mode.
        
        Args:
            output_type: Type of output to check
            
        Returns:
            True if output should be saved
        """
        if self.mode == 'full':
            return True
        
        if self.mode == 'minimal':
            return output_type in self.ESSENTIAL_OUTPUTS
        
        # Summary mode
        if output_type in self.ESSENTIAL_OUTPUTS:
            return True
        if output_type in self.DETAIL_OUTPUTS:
            return False  # Skip detailed per-household data
        if output_type in self.INTERMEDIATE_OUTPUTS:
            return False  # Skip intermediate files
        
        # Default: save for unknown types (conservative)
        return True
    
    def save_summary_statistics(
        self, 
        df: pd.DataFrame, 
        output_path: Path,
        group_by: Optional[List[str]] = None,
        value_cols: Optional[List[str]] = None
    ) -> None:
        """
        Save summary statistics instead of full data.
        
        Args:
            df: DataFrame to summarize
            output_path: Where to save summary
            group_by: Columns to group by (e.g., ['year', 'identity'])
            value_cols: Columns to compute statistics for
        """
        if self.mode == 'full':
            # In full mode, save the actual data
            df.to_csv(output_path, index=False, encoding='utf-8-sig')
            return
        
        # Compute summary statistics
        if group_by and value_cols:
            summary = df.groupby(group_by)[value_cols].agg([
                'count', 'mean', 'std', 'min', 
                ('p25', lambda x: np.percentile(x.dropna(), 25)),
                ('p50', lambda x: np.percentile(x.dropna(), 50)),
                ('p75', lambda x: np.percentile(x.dropna(), 75)),
                'max', 'sum'
            ]).reset_index()
        else:
            # Simple summary of all numeric columns
            summary = df.describe(percentiles=[.25, .5, .75], include='all')
        
        # Save summary
        output_path.parent.mkdir(parents=True, exist_ok=True)
        summary.to_csv(output_path, index=True, encoding='utf-8-sig')
        
        # Also save metadata about what was summarized
        meta_path = output_path.with_suffix('.meta.json')
        metadata = {
            'mode': self.mode,
            'original_rows': len(df),
            'original_cols': len(df.columns),
            'group_by': group_by,
            'value_cols': value_cols,
            'summary_type': 'grouped' if group_by else 'overall'
        }
        with open(meta_path, 'w') as f:
            json.dump(metadata, f, indent=2)
    
    def aggregate_finance_households(
        self, 
        finance_dir: Path,
        years: List[int]
    ) -> pd.DataFrame:
        """
        Aggregate per-household finance data into summary statistics by year and identity.
        
        This replaces saving individual finance_households_YYYY.csv files with 
        a single summary file.
        
        Args:
            finance_dir: Directory containing finance files
            years: List of years to aggregate
            
        Returns:
            DataFrame with aggregated statistics
        """
        summaries = []
        
        for year in years:
            file_path = finance_dir / f"finance_households_{year}.csv"
            if not file_path.exists():
                continue
                
            df = pd.read_csv(file_path)
            
            # Ensure identity column exists
            identity_col = None
            for col in ['identity', 'group', 'tenure']:
                if col in df.columns:
                    identity_col = col
                    break
            
            if identity_col is None:
                # No identity info, aggregate all together
                groups = [('all', df)]
            else:
                groups = [(iden, grp) for iden, grp in df.groupby(identity_col)]
            
            # Aggregate by identity group
            for identity, group_df in groups:
                # Numeric columns to aggregate
                numeric_cols = group_df.select_dtypes(include=[np.number]).columns.tolist()
                
                summary = {
                    'year': year,
                    'identity': identity,
                    'count': len(group_df)
                }
                
                # Compute statistics for key columns
                for col in numeric_cols:
                    if col == 'year':
                        continue
                    values = group_df[col].dropna()
                    if len(values) > 0:
                        summary[f'{col}_mean'] = values.mean()
                        summary[f'{col}_sum'] = values.sum()
                        summary[f'{col}_std'] = values.std()
                        summary[f'{col}_median'] = values.median()
                
                summaries.append(summary)
        
        return pd.DataFrame(summaries)
    
    def get_estimated_size(self) -> Dict[str, float]:
        """
        Estimate storage size for current mode.
        
        Returns:
            Dictionary with size estimates in MB
        """
        estimates = {
            'full': {
                'finance_households': 100,
                'finance_tract': 20,
                'decisions': 80,
                'vulnerability': 30,
                'state_files': 15,
                'excel': 50,
                'visualization': 20,
                'other': 10,
                'total': 325
            },
            'summary': {
                'finance_tract': 0.015,      # 15 KB
                'vulnerability': 0.010,      # 10 KB  
                'decisions_keyyears': 0.030, # 30 KB (4 years × ~7KB)
                'output_summary': 0.002,     # 2 KB
                'total': 0.057               # ~57 KB
            },
            'minimal': {
                'output_summary': 0.002,
                'total': 0.002
            }
        }
        
        return estimates.get(self.mode, estimates['full'])
    
    def create_summary_report(self, output_path: Path) -> None:
        """
        Create a summary report of what was saved/skipped.
        
        Args:
            output_path: Where to save the report
        """
        report = {
            'mode': self.mode,
            'estimated_size_mb': self.get_estimated_size(),
            'statistics_collected': list(self.statistics.keys()),
            'saved_outputs': [],
            'skipped_outputs': []
        }
        
        # Add what was saved/skipped based on mode
        for output_type in (self.ESSENTIAL_OUTPUTS | self.DETAIL_OUTPUTS | self.INTERMEDIATE_OUTPUTS):
            if self.should_save(output_type):
                report['saved_outputs'].append(output_type)
            else:
                report['skipped_outputs'].append(output_type)
        
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w') as f:
            json.dump(report, f, indent=2)
        
        print(f"[SAOutputManager] Summary report saved to {output_path}")
        print(f"[SAOutputManager] Mode: {self.mode}")
        print(f"[SAOutputManager] Estimated size: {report['estimated_size_mb']['total']:.1f} MB")


def create_output_manager(mode: str = 'summary', output_dir: Optional[Path] = None) -> SAOutputManager:
    """
    Factory function to create output manager.
    
    Args:
        mode: Output level - 'full', 'summary', or 'minimal'
        output_dir: Base output directory
        
    Returns:
        SAOutputManager instance
    """
    return SAOutputManager(mode=mode, output_dir=output_dir)
